@startuml

title __STUB's Class Diagram__\n

    interface DAO_STUB {
        {abstract} + loadSerie()
        {abstract} + loadTemporada()
        {abstract} + loadEpisodi()
        {abstract} + loadArtista()
        {abstract} + loadProductora()
        {abstract} + loadAdmin()
        {abstract} + loadClient()
        {abstract} + loadSubscripcio()
        {abstract} + loadVisualització()
        {abstract} + loadValoracio()
    }

  

    class DAO_XML {
        - serie : String
        - temporada : String
        - admin : String
        - client : String
        - episodi : String
        - valoracio : String
        - productora : String
        - artista : String
        - subscripcio : String
        - visualitzacio : String
        + DAO_XML()
        + obtenirDades()
        + loadSerie()
        + loadTemporada()
        + loadEpisodi()
        + loadArtista()
        + loadProductora()
        + loadValoracio()
        + loadAdmin()
        + loadClient()
        + loadSubscripcio()
        + loadVisualització()
        + getSerie()
        + getTemporada()
        + getClient()
        + getAdmin()
        + getEpisodi()
        + getValoracio()
        + getProductora()
        + getArtista()
        + getSubscripcio()
        + getVisualitzacio()
    }
    class STUBXMLParser {
        + STUBXMLParser()
        + parse()
        - obtenirSeries()
        - obtenirProductora()
        - obtenirArtistes()
        - obtenirTemporades()
        - obtenirEpisodis()
        - obtenirValoracions()
        - obtenirAdministradors()
        - obtenirClients()
        - obtenirSubcripcions()
        - obtenirVisualitzacions()
    }

  

  DAO_XML -up-|> DAO_STUB
  STUBXMLParser o-- DAO_XML : daoXml


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
