/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.*;
import javax.naming.ldap.Control;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import controller.Controlador;

/**
 *
 * @author marcosplazagonzalez
 */
public class SearchFrame extends JFrame {
    private Controlador controlador;
    /**
     * Creates new form SearchFrame
     */
    public SearchFrame() {
        initComponents();
        this.controlador = Controlador.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Marcos
    private void initComponents() {
        jLabel1 = new JLabel();
        jTextField1 = new JTextField();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jLabel2 = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Container contentPane = getContentPane();

        //---- jLabel1 ----
        jLabel1.setFont(new Font("AppleGothic", Font.ITALIC, 22));
        jLabel1.setText("CERCADOR ");

        //---- jTextField1 ----
        jTextField1.setForeground(new Color(102, 102, 102));
        jTextField1.setText("Introdueix el nom de la s\u00e8rie...");
        jTextField1.setDoubleBuffered(true);
        jTextField1.addActionListener(e -> jTextField1ActionPerformed(e));

        //---- jButton1 ----
        jButton1.setFont(new Font("AppleGothic", Font.ITALIC, 12));
        jButton1.setText("Cancela");
        jButton1.addActionListener(e -> jButton1ActionPerformed(e));

        //---- jButton2 ----
        jButton2.setFont(new Font("AppleGothic", Font.ITALIC, 12));
        jButton2.setText("Busca");
        jButton2.addActionListener(e -> jButton2ActionPerformed(e));

        //---- jLabel2 ----
        jLabel2.setIcon(new ImageIcon("/Users/marcosplazagonzalez/Desktop/A04VIEW/src/graphicalResources/right-pointing-magnifying-glass_1f50e.png"));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addComponent(jLabel1)
                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 221, GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1)))
                    .addGap(23, 23, 23))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1))
                    .addGap(27, 27, 27))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nomSerie = jTextField1.getText();
        String desc = controlador.buscaSerie(nomSerie);
        if (controlador.buscaSerie(nomSerie) == null) {
            JOptionPane.showMessageDialog(null, "No s'ha trobat cap coincidència!", "ATENCIÓ!", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, nomSerie+"\n\nPlot:\n"+desc, "CERCADOR", JOptionPane.INFORMATION_MESSAGE);
        }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Marcos
    private JLabel jLabel1;
    private JTextField jTextField1;
    private JButton jButton1;
    private JButton jButton2;
    private JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
