/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controller.Controlador;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;


/**
 *
 * @author marcosplazagonzalez
 */
public class STUB_LogInSignIn extends JFrame {
    private Controlador controlador;
    /**
     * Creates new form STUB_LogInSignIn
     */
    private void LogInActionPerformed(ActionEvent e) {
        String username = jTextField1.getText();
        String password = String.valueOf(jPasswordField1.getPassword());

        if(this.controlador.logInUsuari(username, password) == null){
            JOptionPane.showMessageDialog(null, "No s'han trobat coincidències amb el nom d'usuari o la contrasenya!", "ATENCIÓ!", JOptionPane.WARNING_MESSAGE);
        }else{
            this.controlador.logInUsuari(username, password);
            this.dispose();
            MainWindow finestraPrincipal = new MainWindow();
            finestraPrincipal.setVisible(true);
        }
    }

    private void SignInActionPerformed(ActionEvent e) {
        JOptionPane.showMessageDialog(null,"Hem registrat un únic usuari amb nom d'usuari: Test, i contrasenya: 12345678, per a no haver de fer la interfície gráfica de 'Registrar usuari'!","DADA IMPORTANT!", JOptionPane.INFORMATION_MESSAGE);
    }

    private void cancel1ActionPerformed(ActionEvent e) {
        this.dispose();
    }

    public STUB_LogInSignIn() {
        initComponents();
        this.controlador = Controlador.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Marcos
    private void initComponents() {
        jLabel3 = new JLabel();
        jLabel2 = new JLabel();
        jTextField1 = new JTextField();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jPasswordField1 = new JPasswordField();
        SignIn = new JButton();
        LogIn = new JButton();
        label1 = new JLabel();
        cancel1 = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Container contentPane = getContentPane();

        //---- jLabel3 ----
        jLabel3.setFont(new Font("Impact", Font.ITALIC, 26));
        jLabel3.setText("SERIES TIME UB");

        //---- jLabel2 ----
        jLabel2.setFont(new Font("AppleGothic", Font.ITALIC, 14));
        jLabel2.setText("Inici de sessi\u00f3");

        //---- jTextField1 ----
        jTextField1.setFont(new Font("AppleGothic", Font.ITALIC, 12));
        jTextField1.setForeground(new Color(102, 102, 102));
        jTextField1.setText("Introdueix el nom d'usuari...");

        //---- jLabel4 ----
        jLabel4.setFont(new Font("AppleGothic", Font.ITALIC, 12));
        jLabel4.setText("Nom d'usuari:");

        //---- jLabel5 ----
        jLabel5.setFont(new Font("AppleGothic", Font.ITALIC, 12));
        jLabel5.setText("Contrasenya:");

        //---- jLabel6 ----
        jLabel6.setFont(new Font("AppleGothic", Font.ITALIC, 12));
        jLabel6.setText("Encara no t'has registrat?");

        //---- SignIn ----
        SignIn.setFont(new Font("AppleGothic", Font.ITALIC, 12));
        SignIn.setText("Registra't");
        SignIn.addActionListener(e -> SignInActionPerformed(e));

        //---- LogIn ----
        LogIn.setFont(new Font("AppleGothic", Font.ITALIC, 12));
        LogIn.setText("Inicia la sessi\u00f3");
        LogIn.addActionListener(e -> LogInActionPerformed(e));

        //---- label1 ----
        label1.setIcon(new ImageIcon("/Users/marcosplazagonzalez/Desktop/A04-A04Vista/src/graphicalResources/little.png"));

        //---- cancel1 ----
        cancel1.setText("Sortir");
        cancel1.setFont(new Font("AppleGothic", Font.ITALIC, 13));
        cancel1.addActionListener(e -> cancel1ActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGroup(contentPaneLayout.createParallelGroup()
                                        .addComponent(jLabel4)
                                        .addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                    .addGroup(contentPaneLayout.createParallelGroup()
                                        .addComponent(SignIn)
                                        .addComponent(jLabel6)))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel2))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                                    .addComponent(label1))
                                .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(LogIn)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                                    .addComponent(cancel1)))
                            .addGap(36, 36, 36))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(0, 0, Short.MAX_VALUE))))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(label1)
                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(SignIn)
                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addComponent(jLabel5)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(LogIn)
                        .addComponent(cancel1))
                    .addContainerGap(12, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Marcos
    private JLabel jLabel3;
    private JLabel jLabel2;
    private JTextField jTextField1;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JPasswordField jPasswordField1;
    private JButton SignIn;
    private JButton LogIn;
    private JLabel label1;
    private JButton cancel1;
    // End of variables declaration//GEN-END:variables
}
