/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controller.Controlador;
import model.Serie;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

/**
 *
 * @author Yuste32
 */
public class ValorateSelection extends javax.swing.JFrame {

    Controlador contr;
    Serie se;
    int temp;
    int ep;

    public ValorateSelection(Controlador contr, Serie se, int temp, int ep) {
        this.contr = contr;
        this.se = se;
        this.temp = temp;
        this.ep = ep;

        initComponents();
        String s;
        lblSe.setText(se.getTitle());
        s = "Temp: ";
        s += Integer.toString(temp);
        lblTemp.setText(s);
        s = "Ep: ";
        s += Integer.toString(ep);
        lblEp.setText(s);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Quim Yuste
    private void initComponents() {
        bGood = new JButton();
        bFunny = new JButton();
        bWow = new JButton();
        bSad = new JButton();
        bMeh = new JButton();
        bBad = new JButton();
        lblSe = new JLabel();
        lblTemp = new JLabel();
        lblEp = new JLabel();
        bCancel = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Container contentPane = getContentPane();

        //---- bGood ----
        bGood.setText("Good");
        bGood.addActionListener(e -> bGoodActionPerformed(e));

        //---- bFunny ----
        bFunny.setText("Funny");
        bFunny.addActionListener(e -> bFunnyActionPerformed(e));

        //---- bWow ----
        bWow.setText("Wow");
        bWow.addActionListener(e -> bWowActionPerformed(e));

        //---- bSad ----
        bSad.setText("Sad");
        bSad.addActionListener(e -> bSadActionPerformed(e));

        //---- bMeh ----
        bMeh.setText("Meh");
        bMeh.addActionListener(e -> bMehActionPerformed(e));

        //---- bBad ----
        bBad.setText("Bad");
        bBad.addActionListener(e -> bBadActionPerformed(e));

        //---- lblSe ----
        lblSe.setFont(new Font("Tahoma", Font.PLAIN, 18));
        lblSe.setHorizontalAlignment(SwingConstants.CENTER);
        lblSe.setText("Serie");

        //---- lblTemp ----
        lblTemp.setHorizontalAlignment(SwingConstants.CENTER);
        lblTemp.setText("Temp");

        //---- lblEp ----
        lblEp.setHorizontalAlignment(SwingConstants.CENTER);
        lblEp.setText("Ep");

        //---- bCancel ----
        bCancel.setText("Cancel\u00b7la");
        bCancel.addActionListener(e -> bCancelActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bWow, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bGood, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bFunny, GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                    .addGap(9, 9, 9)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(bMeh, GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addComponent(bSad, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bBad, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(lblTemp)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEp)
                    .addGap(53, 53, 53))
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(bCancel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblSe, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(lblSe)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTemp)
                        .addComponent(lblEp))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(bGood)
                        .addComponent(bSad))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(bMeh)
                        .addComponent(bFunny))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(bWow)
                        .addComponent(bBad))
                    .addGap(18, 18, 18)
                    .addComponent(bCancel)
                    .addContainerGap(22, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void bGoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGoodActionPerformed
        contr.valorarEpisodi(6,"",ep,temp,se.getId());
        this.dispose();
    }//GEN-LAST:event_bGoodActionPerformed

    private void bFunnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFunnyActionPerformed
        contr.valorarEpisodi(5,"",ep,temp,se.getId());
        this.dispose();
    }//GEN-LAST:event_bFunnyActionPerformed

    private void bWowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWowActionPerformed
        contr.valorarEpisodi(4,"",ep,temp,se.getId());
        this.dispose();
    }//GEN-LAST:event_bWowActionPerformed

    private void bSadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSadActionPerformed
        contr.valorarEpisodi(3,"",ep,temp,se.getId());
        this.dispose();
    }//GEN-LAST:event_bSadActionPerformed

    private void bMehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMehActionPerformed
        contr.valorarEpisodi(2,"",ep,temp,se.getId());
        this.dispose();
    }//GEN-LAST:event_bMehActionPerformed

    private void bBadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBadActionPerformed
        contr.valorarEpisodi(1,"",ep,temp,se.getId());
        this.dispose();
    }//GEN-LAST:event_bBadActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Quim Yuste
    private JButton bGood;
    private JButton bFunny;
    private JButton bWow;
    private JButton bSad;
    private JButton bMeh;
    private JButton bBad;
    private JLabel lblSe;
    private JLabel lblTemp;
    private JLabel lblEp;
    private JButton bCancel;
    // End of variables declaration//GEN-END:variables
}
